a=int(input("Enter value for a: "))
b=int(input("Enter value for b: "))
print(a, "+", b, "=", a+b) # Addition
print(a, "-", b, "=", a-b) # Subtraction
print(a, "*", b, "=", a*b) # Multiplication
print(a, "/", b, "=", a/b) # Division
print(a, "//", b, "=", a//b) # Floor Division
print(a, "**", b, "=", a**b) # Exponential
print(a, "%", b, "=", a%b) # Modulus